repos:
-   repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.26.0
    hooks:
    - id: yapf
      args: ['--style=.style.yapf', '--parallel', '--in-place']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
