#@  def get_config_parameters():
#@      for surrogate in ["resnet18"]:
#@          for sigma in [20, 24, 28, 32]:
#@                          yield {"surrogate": surrogate, "sigma":sigma}

---

attack_regime:
  name : transfer-regime-multiple-targets
  show_images : False
  skip_already_adversarial: False
  dont_save_images: False
  results_dir: results/augment_noise_sample/{surrogate}/{sigma}

  attack_algorithm: 
    name: apgd
    n_iters: 60
    eot_iter: 20

  epsilon: 10
  norm: l2
  # batch_size: 256
  batch_size: 3

  surrogate:
    model_type: local
    name: {surrogate}
    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0
    
    augmentations:
      - name: gaussian-noise
        std: {sigma}

  dataset_config:
    data_dir: datasets/imagenet_val_256_rescaled_224_center_cropped_first_2000
    dataset_type: imagenet-validation
    load_only_organisms: True
    size_limit: 3

  multiple_target_configs:
    model_type: local
    names:
      - resnet18

    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0

