#@  def get_config_parameters():
#@      std = 15
#@      yield {"eot_iter": 10, "n_iters": 25, "augment_name": "gaussian-noise", "param": 15, "param_yaml": "std: " + str(std)}
#@      std = 0
#@      yield {"eot_iter": 1, "n_iters": 16, "augment_name": "gaussian-noise", "param": 0, "param_yaml": "std: " + str(std)}
#@      yield {"eot_iter": 1, "n_iters": 32, "augment_name": "gaussian-noise", "param": 0, "param_yaml": "std: " + str(std)}
#@      yield {"eot_iter": 1, "n_iters": 64, "augment_name": "gaussian-noise", "param": 0, "param_yaml": "std: " + str(std)}
#@      yield {"eot_iter": 1, "n_iters": 128, "augment_name": "gaussian-noise", "param": 0, "param_yaml": "std: " + str(std)}

---

attack_regime:
  name : transfer-regime-multiple-targets
  show_images : False
  skip_already_adversarial: False
  dont_save_images: True
  results_dir: results/ensemble_exp/wide_resnet50_2_efficientnet-b0-advtrain_squeezenet/{augment_name}_{param}_eot_iter_{eot_iter}_n_iters_{n_iters}/

  attack_algorithm: 
    name: apgd
    n_iters: {n_iters}
    eot_iter: {eot_iter}

  epsilon: 10
  norm: l2
  batch_size: 64
  # batch_size: 1

  surrogate:
    model_type: ensemble
    model_configs:
      - name: wide_resnet50_2
        model_type: local

      - name: efficientnet-b0-advtrain
        model_type: local

      - name: squeezenet
        model_type: local

    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0
    
    augmentations:
      - name: {augment_name}
        {param_yaml}

  dataset_config:
    data_dir: datasets/imagenet_val_256_rescaled_224_center_cropped_first_2000
    dataset_type: imagenet-validation
    load_only_organisms: True
    size_limit: 500
    # size_limit: 2

  multiple_target_configs:
    model_type: local
    names:
      - wide_resnet50_2
      - resnet18
      - resnet50
      - resnext50_32x4d
      - efficientnet-b0
      - efficientnet-b0-advtrain
      - densenet-121
      - squeezenet

    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0

