---

attack_regime:
  name : transfer-regime 
  show_images : False
  skip_already_adversarial: False
  dont_save_images: True
  results_dir: results/baseline_test

  attack_algorithm: 
    name: passthrough 

  epsilon: 0.0
  batch_size: 20
  norm: linf

  dataset_config:
    data_dir: datasets/imagenet_val_256_rescaled_224_center_cropped
    dataset_type: imagenet-validation
    load_only_organism: True
    size_limit: 10000

  target_model_config:
    model_type: local
    name: resnet18
    output_mapping: "organism_margin"

    loss:
      name: margin_loss
      margin: 0.0