#@  def get_config_parameters():
#@      for eot_iter in [1, 3, 10, 30, 100]:
#@          n_iters = 30
#@          yield {"eot_iter": eot_iter, "n_iters": n_iters, "surrogate": "resnet18"}

---

attack_regime:
  name : transfer-regime-multiple-targets
  show_images : False
  skip_already_adversarial: False
  dont_save_images: False
  results_dir: results/noise_eot_iter_exp/{surrogate}/eot_iter_{eot_iter}_n_iters_{n_iters}_std_35

  attack_algorithm: 
    name: apgd
    n_iters: {n_iters}
    eot_iter: {eot_iter}

  epsilon: 10
  norm: l2
  batch_size: 256

  surrogate:
    model_type: local
    name: {surrogate}

    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0
    
    augmentations:
      - name: gaussian-noise
        std: 35

  dataset_config:
    data_dir: datasets/imagenet_val_256_rescaled_224_center_cropped_first_2000
    dataset_type: imagenet-validation
    load_only_organisms: True
    size_limit: 500

  multiple_target_configs:
    model_type: local
    names:
      - wide_resnet50_2
      - resnet18
      - resnet50
      - resnext50_32x4d
      - efficientnet-b0
      - efficientnet-b0-advtrain
      - densenet-121
      - squeezenet

    output_mapping: organism_margin

    loss:
      name: margin_loss
      margin: 0.0

