---

attack_regime:
  name : transfer-regime 
  show_images : False
  skip_already_adversarial: False

  attack_algorithm: 
    name: apgd
    n_iters: 50

  epsilon: 20
  norm: l2
  batch_size: 2

  surrogate:
    model_type: local
    name: efficientnet-b0-advtrain

    loss:
      name: margin_loss
      margin: 0.0

  dataset_config:
    data_dir: datasets/imagenet_val_256_rescaled_224_center_cropped
    dataset_type: imagenet-validation
    load_only_organisms: True
    size_limit: 100

  target_model_config:
    model_type: local
    name: resnet18
    resize_and_center_crop: False

    loss:
      name: margin_loss
      margin: 0.0


